/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/X5dvgxHzp1D
 */
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function ErrorForm() {
  return (
    <main className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-md p-4 bg-white rounded shadow dark:bg-gray-800">
        <h1 className="text-2xl font-bold mb-4">Interactive Form</h1>
        <form className="space-y-4">
          <div className="flex flex-wrap gap-2">
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">+</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">Word1</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">+</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">Word2</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">+</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">Word3</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">+</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">Word4</Button>
            <Button className="px-2 py-1 bg-gray-200 dark:bg-gray-700">+</Button>
          </div>
          <div className="border-t border-gray-200 dark:border-gray-700 pt-4">
            <p className="mb-2">Clicked Word:</p>
            <p className="text-lg font-semibold mb-4">Word1</p>
            <div className="flex flex-col space-y-2">
              <Label htmlFor="word">Edit Word</Label>
              <Input defaultValue="Word1" id="word" />
              <Label htmlFor="grammar">Grammar Error</Label>
              <select
                className="w-full p-2 border border-gray-300 rounded dark:bg-gray-700 dark:text-white"
                id="grammar"
              >
                <option value="">Select an error</option>
                <option value="spelling">Spelling</option>
                <option value="tense">Tense</option>
                <option value="structure">Sentence Structure</option>
              </select>
              <Label htmlFor="punctuation">Punctuation Error</Label>
              <select
                className="w-full p-2 border border-gray-300 rounded dark:bg-gray-700 dark:text-white"
                id="punctuation"
              >
                <option value="">Select an error</option>
                <option value="comma">Comma</option>
                <option value="semicolon">Semicolon</option>
                <option value="period">Period</option>
              </select>
            </div>
            <Button className="w-full mt-4 py-2 bg-gray-600 text-white rounded">Submit</Button>
          </div>
        </form>
      </div>
    </main>
  )
}
